package alignment;

public class Tester {
	public static void main(String[] args) {
		Alignment a = new Local(new SequencePair("HPICEVSKVASHLEVNCDKRNLTALPPDLPKDTTILHLSENLLYTFSLATLMPYTRLTQLNLDRAELTKLQVDGTLPVLGTLDLSHNQLQSLPLLGQTLPALTVLDVSFNRLTSLPLGALRGLGELQELYLKGNELKTLPPGLLTPTPKLEKLSLANNNLTELPAGLLNGLENLDTLLLQENSLYTIPKGFFGSHLLPFAFLHGNPWLCNCEILYFRRWLQDNAENVYVWKQGVDVKAMTSNVASVQCDNSDKFPVYKYPGKGCPTLGDEGDTDLDYPEED", "GRFEILEKNGKMYILDGAHNPHGAESLVRSLKLYFNGEPLSLVIGILDDKNREDILRKYTGIFERVIVTRVPSPRMKDMNSLVDMAKKFFKNVEVIEDPLEAIESTERATVVTGSLFLVGYVREFLTTGKINEEWK"), new GapFunction(-4, 0), new ScoringMatrix("/home/proj/biocluster/praktikum/bioprakt/Data/MATRICES/blosum62.mat"));
		a.make();
	}
}
